# Use the official ROS 2 Foxy desktop image as the base
FROM osrf/ros:foxy-desktop-focal

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=foxy

# Install necessary ROS 2 packages for Gazebo, Cartographer, and Navigation2
RUN apt-get update && apt-get install -y \
    qtwayland5 \
    ros-foxy-rviz2 \
    ros-foxy-gazebo-* \
    ros-foxy-cartographer \
    ros-foxy-cartographer-ros \
    ros-foxy-navigation2 \
    ros-foxy-nav2-bringup \
    ros-foxy-dynamixel-sdk \
    ros-foxy-turtlebot3-msgs \
    ros-foxy-turtlebot3

# Set up the ROS environment and add sourcing commands to .bashrc
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> ~/.bashrc && \
    echo "export ROS_DOMAIN_ID=30 #TURTLEBOT3" >> ~/.bashrc && \
    echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /root/.bashrc

RUN mkdir -p ~/turtlebot3_ws/src && cd ~/turtlebot3_ws/src/
RUN git clone -b foxy-devel https://github.com/ROBOTIS-GIT/turtlebot3_simulations.git
RUN cd ~/turtlebot3_ws && colcon build --symlink-install
# Source the ROS environment for the default shell session
RUN /bin/bash -c "source ~/.bashrc"

# Set default command
CMD ["bash"]
