services:
  ros: # Service name
    image: ros2-foxy-remote-tb3 # Specifies the Docker image to use for this service
    container_name: ros2-foxy-tb3-remote-intel-xserver # Sets the container name to "ros"
    network_mode: host # Uses the host's networking stack (container shares the host's network)
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # Mounts the X11 Unix socket for GUI applications
      - /etc/localtime:/etc/localtime:ro # Mounts the local timezone file in read-only mode to sync container time
      - /dev/:/dev/ # Mounts the /dev directory to access host devices
      - /dev/dri:/dev/dri # Mounts the Direct Rendering Infrastructure (DRI) device for GPU support
    environment:
      - color_prompt=yes # Environment variable for colored prompts
      - DISPLAY=:0 # Passes the DISPLAY environment variable for X11 forwarding
      - TERM # Passes the TERM environment variable for terminal settings
      - QT_X11_NO_MITSHM=1 # Prevents MIT-SHM extension usage for X11, useful for remote displays
      - DRI_NAME=card0 # Ensures the correct DRI device is used for Intel integrated graphics
    tty: true # Allocates a TTY for the container, useful for interactive shells    
    stdin_open: true # Keeps stdin open to support interactive processes
    devices:
      - /dev/:/dev/ # Maps the /dev directory to access host devices (repeated for completeness)
