services:
  ros: # Service name
    image: ros2-foxy-remote-tb3 # Specifies your custom Docker image
    container_name: ros2-foxy-tb3-remote-nvidia-wayland # Sets the container name to "ros"
    network_mode: host # Uses the host's networking stack (container shares the host's network)
    volumes:
      - /run/user/1000/wayland:/run/user/1000/wayland # Mounts the Wayland socket for GUI applications
      - /etc/localtime:/etc/localtime:ro # Mounts the local timezone file in read-only mode to sync container time
      - /dev/:/dev/ # Mounts the /dev directory to access host devices
      - /dev/dri:/dev/dri # Mounts the Direct Rendering Infrastructure (DRI) device for GPU support
      - /dev/shm:/dev/shm
      - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/run/user/1000/$WAYLAND_DISPLAY
    environment:
      - EGL_PLATFORM=wayland
      - color_prompt=yes # Environment variable for colored prompts
      - WAYLAND_DISPLAY=wayland-0 # Passes the Wayland display socket
      - XDG_RUNTIME_DIR=/run/user/1000
      - TERM # Passes the TERM environment variable for terminal settings
      - QT_QPA_PLATFORM=wayland # Configures Qt to use the Wayland platform
      - NVIDIA_VISIBLE_DEVICES=all # Makes all NVIDIA devices visible to the container
      - NVIDIA_DRIVER_CAPABILITIES=all # Grants all NVIDIA driver capabilities to the container
      - __NV_PRIME_RENDER_OFFLOAD=1 # Enables NVIDIA PRIME render offload
      - __GLX_VENDOR_LIBRARY_NAME=nvidia # Specifies the GLX vendor library to use (NVIDIA)
    tty: true # Allocates a TTY for the container, useful for interactive shells    
    stdin_open: true # Keeps stdin open to support interactive processes
    devices:
      - /dev/:/dev/ # Maps the /dev directory to access host devices (repeated for completeness)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia # Specifies the NVIDIA driver
              count: all # Allocates all available GPUs
              capabilities: [gpu] # Requests GPU capabilities
    runtime: nvidia # Uses the NVIDIA runtime for GPU support